profile: iterate

shared:
  ingress_domain: "iterate.h2o-4-7575.h2o.vmware.com"
  kubernetes_distribution: ""
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    MIIFtzCCA5+gAwIBAgIUKfT/TDzAXS2kygIaBXLQZ1jr6hAwDQYJKoZIhvcNAQEL
    BQAwUTELMAkGA1UEBhMCQ04xDDAKBgNVBAgMA1BFSzEQMA4GA1UEBwwHQmVpSmlu
    ZzEPMA0GA1UECgwGVk13YXJlMREwDwYDVQQDDAhIYXJib3JDQTAeFw0yMzAzMDEx
    NTM0MzNaFw0zMzAyMjYxNTM0MzNaMGkxCzAJBgNVBAYTAkNOMQwwCgYDVQQIDANQ
    RUsxEDAOBgNVBAcMB0JlaUppbmcxDzANBgNVBAoMBlZNd2FyZTEpMCcGA1UEAwwg
    aGFyYm9yLmgyby00LTc1NzUuaDJvLnZtd2FyZS5jb20wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCtCptkBj2x4mnbpfnuznz/5KwcIFv630mhxgSYFFY2
    TbPv/FeGIYUDiGoFR/yQl4/xM4TFfpcV9GsRrTYQtuwtkvxlvbMcwuM0f9FSwYVo
    qGsazXLwA81Y5GUYJz0uMKcuhvFAI1IyG1rsVBRFW+c5Rc51gpHkLAzTsbAigOL/
    92xXxfk2VxxG7+k0W1QCRJfJerAoll+tTJeNO+d6ZEuCI0u5/SMSDIBYhHqu4awt
    RN94lhSQk7BN3NkLxkkZxFSEQj02Jm6WFH3FoONx0ESXxPau1B4yvwxiELOG5eQm
    O5s0IVQMzfb0z+DU9GPSI9yrmEMAcITXGhHa49dzjYuSepWei5Xvbv2B+6U5tHZD
    MrlhM6gN892amuJRM3vILoU4p1L5EokFtYLXVY1hVDsFF/NI3i+Z0nVlc2gPbPBd
    OUhuppan0gnl2aUrixYEd3H4GCzpTXnzoM9CWOz3pBbiBh4DHPWZnctwnczRE5PA
    kND4VGXJOvmZZpFZ+5SV0OH4yMO90Qu2x7F29kzXfDhrKmukjxPBsMAupt+tbTVV
    VwyWUQ7dXEwa1ImnNoYOobJLRj+DgRsjCpV9mFSQVja15TmLDYT2vDP7N6f2j4rY
    t4KJII99ZalBPHsV8Nj9D954P0ifQ4WdWqM//02Vut3okaTKo57+7Z/NNGOR87ur
    OQIDAQABo28wbTArBgNVHREEJDAigiBoYXJib3IuaDJvLTQtNzU3NS5oMm8udm13
    YXJlLmNvbTAdBgNVHQ4EFgQUTBZuYch/uMihaFfZVO0gnAdIUnQwHwYDVR0jBBgw
    FoAUb1jAAjl/Qt2bdXwqQKdnP2M+HPowDQYJKoZIhvcNAQELBQADggIBAI+yvlhF
    85tCvHkw/mclFcSvQNhIY7W18ukXiasmJ3z7DnnMwj+4Sr0Vw0/TazvqbFpXkyZX
    5rFqK4uSicfb5spBZLGOkk74xbEinNRcyIMSvEPdRENTL+46Oh7yKqOBtb7JuvKQ
    13epzZt7qUQ24SQApRFEx7X/tTglUyWYxp5dyOFrDtXz0oGwLliZcnBOA7TQIlSI
    YzJv7cHCrVoRgg+82xxrn3ZWgJhjzxfIOdKj24+WoUFyaSf3ZdCUy1b/aAS4gCy+
    M+P6U+BqMmFMuseuD8Yh18yWxZWgHZ2QthtZJ/luYEMfMbTkqCuFRztYc0gRVLsq
    KZ3ChXQb5vMglQDH1fzbwvq0Ep6IgCoJ14HpUhW3BP6Q31xFyeAJlKPbtNK/YfHe
    EEI4vI/1Cbuce1z1wqcZMgHeH42ObfwK1ta6C7YHVv9KY3BuOIhH5lLKiASzr/3o
    01YJ9sPDo0VuK9d2bxeOjBtEKRdTuL6TrUkhuvRPMl/aALmDWdV+Jm03N0VVvL5l
    1YvNgrXxqAWhkJ6u9eyhmMK3lISrmBPdM4mJvFCRcoqPRo4Y7lNQm8Jwlp860mbL
    v6DPNB8Pug/jx6aS0Nv/vv/N6CMXprbk5BZEuu9S6XdupU5g0/cSSa3AP75gJKKF
    97G36qFEcCz3GzwNkrvwo3M8+1pI24vn8H8g
    -----END CERTIFICATE-----
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

buildservice:
  exclude_dependencies: true


supply_chain: basic

image_policy_webhook:
  allow_unmatched_tags: true

contour:
  envoy:
    service:
      type: LoadBalancer # (Optional) Defaults to LoadBalancer.

appliveview_connector:
  backend:
    sslDeactivated: true
    ingressEnabled: true
    host: appliveview.view.vc01.h2o-4-7575.h2o.vmware.com

